var messageType = {
  PIXEL_INSPECTOR : "pixelInspector",
  CALL_STACK : "callStack",
  FUNCTION_HISTOGRAM : "functionHistogram",
  TOGGLE_PROGRAM_USAGE_COUNT : "toggleProgramUsageCount",
  RESET_PROGRAM_USAGE_COUNT : "resetProgramUsageCount",
  GET_PROGRAM_USAGE_COUNT : "getProgramUsageCount",
  TOGGLE_DUPLICATE_PROGRAM_USAGE : "toggleDuplicateProgramUsage",
  GET_DUPLICATE_PROGRAM_USAGE : "getDuplicateProgramUse",
  GET_CONTEXTS : "getContexts",
  CONTEXTS : "contexts",
  GET_TEXTURE : "texture",
  GET_TEXTURES : "textures",
  GET_BUFFERS : "buffers",
  GET_FRAME_BUFFERS : "frameBuffers",
  GET_RENDER_BUFFERS : "renderBuffers",
}
