var messageType = {
  PIXEL_INSPECTOR : "pixelInspector",
  CALL_STACK : "callStack",
  FUNCTION_HISTOGRAM : "functionHistogram",
  BEGIN_PROGRAM_USAGE_COUNT : "beginProgramUsageCount",
  STOP_PROGRAM_USAGE_COUNT : "stopProgramUsageCount",
  RESET_PROGRAM_USAGE_COUNT : "resetProgramUsageCount",
  GET_PROGRAM_USAGE_COUNT : "getProgramUsageCount",
  TOGGLE_DUPLICATE_PROGRAM_USAGE : "toggleDuplicateProgramUsage",
  GET_DUPLICATE_PROGRAM_USAGE : "getDuplicateProgramUse",
  GET_CONTEXTS : "getContexts",
  CONTEXTS : "contexts",
  TEXTURE : "texture",
  TEXTURE_LIST : "textures",
}
