var messageType = {
  PIXEL_INSPECTOR : "pixelInspector",
  GET_CALL_STACK : "getCallStack",
  TOGGLE_CALL_STACK : "toggleCallStack",
  TOGGLE_FUNCTION_HISTOGRAM : "toggleFunctionHistogram",
  FUNCTION_HISTOGRAM : "functionHistogram",
  TOGGLE_PROGRAM_USAGE_COUNT : "toggleProgramUsageCount",
  RESET_PROGRAM_USAGE_COUNT : "resetProgramUsageCount",
  GET_PROGRAM_USAGE_COUNT : "getProgramUsageCount",
  TOGGLE_DUPLICATE_PROGRAM_USAGE : "toggleDuplicateProgramUsage",
  GET_DUPLICATE_PROGRAM_USAGE : "getDuplicateProgramUse",
  RESET_DUPLICATE_PROGRAM_USAGE : "resetDuplicateProgramUsage",
  GET_CONTEXTS : "getContexts",
  CONTEXTS : "contexts",
  GET_TEXTURE : "texture",
  GET_TEXTURES : "textures",
  GET_BUFFER : "buffer",
  GET_BUFFERS : "buffers",
  GET_FRAME_BUFFER : "frameBuffer",
  GET_FRAME_BUFFERS : "frameBuffers",
  GET_RENDER_BUFFER : "renderBuffer",
  GET_RENDER_BUFFERS : "renderBuffers",
  STATE_VARS : "stateVariables",
}
